// Command genrlccfixture is a code generator for the rlccclient and
// flccclient packages. It parses a chart's values.yaml and emits a
// fixture_gen.go containing the in-memory catalog map.
//
// Two modes:
//
//	-mode rlcc   parses internal/rlccclient/testdata/rlcc-values.yaml
//	             and writes internal/rlccclient/fixture_gen.go (default).
//	-mode flcc   parses internal/flccclient/testdata/flcc-values.yaml
//	             and writes internal/flccclient/fixture_gen.go.
//
// Run via go generate (directives live in client.go in each target package).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"text/template"

	"qac/internal/flccclient"
	"qac/internal/rlccclient"
)

var rlccTpl = template.Must(template.New("rlcc").Parse(`// Code generated by cmd/genrlccfixture; DO NOT EDIT.
package rlccclient

const FixtureChartTag = {{ printf "%q" .ChartTag }}
const FixtureSHA = {{ printf "%q" .SHA }}

var Fixture = map[string]WorkflowGraph{
{{- range .Names }}
	{{ printf "%q" . }}: {{ index $.Graphs . | printf "%#v" }},
{{- end }}
}
`))

var flccTpl = template.Must(template.New("flcc").Parse(`// Code generated by cmd/genrlccfixture; DO NOT EDIT.
package flccclient

const FixtureChartTag = {{ printf "%q" .ChartTag }}
const FixtureSHA = {{ printf "%q" .SHA }}

var Fixture = map[string]FLCCWorkflowGraph{
{{- range .Names }}
	{{ printf "%q" . }}: {{ index $.Graphs . | printf "%#v" }},
{{- end }}
}
`))

type rlccTplData struct {
	ChartTag string
	SHA      string
	Names    []string
	Graphs   map[string]rlccclient.WorkflowGraph
}

type flccTplData struct {
	ChartTag string
	SHA      string
	Names    []string
	Graphs   map[string]flccclient.FLCCWorkflowGraph
}

func main() {
	mode := flag.String("mode", "rlcc", "rlcc or flcc")
	in := flag.String("in", "", "input YAML path (required)")
	out := flag.String("out", "", "output Go path (required)")
	chartTag := flag.String("tag", "", "FixtureChartTag value")
	sha := flag.String("sha", "vendored", "FixtureSHA value")
	flag.Parse()
	if *in == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "genrlccfixture: -in and -out are required")
		os.Exit(2)
	}

	body, err := os.ReadFile(*in)
	must(err, "read %s", *in)

	var rendered string
	switch *mode {
	case "rlcc":
		m, err := rlccclient.ParseValuesYAML(bytes.NewReader(body))
		must(err, "parse rlcc")
		names := sortedKeys(m)
		var buf bytes.Buffer
		must(rlccTpl.Execute(&buf, rlccTplData{ChartTag: *chartTag, SHA: *sha, Names: names, Graphs: m}), "render rlcc")
		// %#v includes the package qualifier when printing types from another
		// package (e.g. "rlccclient.WorkflowGraph{...}"). Since fixture_gen.go
		// lives inside package rlccclient, strip the qualifier so the output compiles.
		rendered = strings.ReplaceAll(buf.String(), "rlccclient.", "")
	case "flcc":
		m, err := flccclient.ParseValuesYAML(bytes.NewReader(body))
		must(err, "parse flcc")
		names := sortedFLCCKeys(m)
		var buf bytes.Buffer
		must(flccTpl.Execute(&buf, flccTplData{ChartTag: *chartTag, SHA: *sha, Names: names, Graphs: m}), "render flcc")
		// Same qualifier-stripping for the flccclient package.
		rendered = strings.ReplaceAll(buf.String(), "flccclient.", "")
	default:
		fmt.Fprintf(os.Stderr, "genrlccfixture: unknown -mode %q\n", *mode)
		os.Exit(2)
	}

	formatted, err := format.Source([]byte(rendered))
	must(err, "gofmt")
	must(os.WriteFile(*out, formatted, 0o644), "write %s", *out)
	fmt.Fprintf(os.Stderr, "genrlccfixture: wrote %s\n", *out)
}

func sortedKeys(m map[string]rlccclient.WorkflowGraph) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedFLCCKeys(m map[string]flccclient.FLCCWorkflowGraph) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func must(err error, fmtStr string, args ...any) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "genrlccfixture: "+fmtStr+": %v\n", append(args, err)...)
		os.Exit(1)
	}
}
