//go:generate go run ../../cmd/genrlccfixture -mode flcc -in testdata/flcc-values.yaml -out fixture_gen.go -tag develop@2026-05-29 -sha vendored

package flccclient

import (
	"context"
	"errors"
	"fmt"
	"sort"
)

// ErrWorkflowNotFound is returned by GetWorkflow and TerminalPhase when the
// named workflow is not in the catalog.
var ErrWorkflowNotFound = errors.New("flcc workflow not found")

// Client is the read-only FLCC catalog. TerminalPhase is the load-bearing
// extra over RLCC: the iter-5b step rail calls it to resolve
// components.computetray.workflow -> "waits for <terminal>" labels.
type Client interface {
	ListWorkflows(ctx context.Context) ([]FLCCWorkflowSummary, SourceRef, error)
	GetWorkflow(ctx context.Context, name string) (FLCCWorkflowGraph, SourceRef, error)
	TerminalPhase(ctx context.Context, name string) (string, error)
}

// MapClient is backed by an in-memory Fixture. The Fixture is filled in by
// fixture_gen.go (generated by cmd/genrlccfixture) — Task 17 wires that up.
type MapClient struct {
	fixture map[string]FLCCWorkflowGraph
	source  SourceRef
}

// NewMapClient returns a MapClient backed by the package-level Fixture map.
// SourceRef reports the chart tag from the vendored snapshot header.
func NewMapClient() *MapClient {
	return &MapClient{
		fixture: Fixture,
		source:  SourceRef{ChartTag: FixtureChartTag, SHA: FixtureSHA},
	}
}

func (c *MapClient) ListWorkflows(_ context.Context) ([]FLCCWorkflowSummary, SourceRef, error) {
	out := make([]FLCCWorkflowSummary, 0, len(c.fixture))
	for _, g := range c.fixture {
		out = append(out, g.FLCCWorkflowSummary)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, c.source, nil
}

func (c *MapClient) GetWorkflow(_ context.Context, name string) (FLCCWorkflowGraph, SourceRef, error) {
	g, ok := c.fixture[name]
	if !ok {
		return FLCCWorkflowGraph{}, c.source, fmt.Errorf("%w: %s", ErrWorkflowNotFound, name)
	}
	return g, c.source, nil
}

func (c *MapClient) TerminalPhase(_ context.Context, name string) (string, error) {
	g, ok := c.fixture[name]
	if !ok {
		return "", fmt.Errorf("%w: %s", ErrWorkflowNotFound, name)
	}
	return g.TerminalPhase, nil
}
