//go:generate go run ../../cmd/genrlccfixture -mode rlcc -in testdata/rlcc-values.yaml -out fixture_gen.go -tag v3.87.0 -sha vendored

package rlccclient

import (
	"context"
	"errors"
	"fmt"
	"sort"
)

// ErrWorkflowNotFound is returned by GetWorkflow when the named workflow
// is not in the catalog.
var ErrWorkflowNotFound = errors.New("rlcc workflow not found")

// Client is the read-only RLCC workflow catalog. Two impls: MapClient
// (test + offline) and SourcegraphClient (production).
type Client interface {
	ListWorkflows(ctx context.Context) ([]WorkflowSummary, SourceRef, error)
	GetWorkflow(ctx context.Context, name string) (WorkflowGraph, SourceRef, error)
}

// MapClient is backed by an in-memory Fixture. The Fixture is filled in by
// fixture_gen.go (generated by cmd/genrlccfixture) — Task 10 wires that up.
type MapClient struct {
	fixture map[string]WorkflowGraph
	source  SourceRef
}

// NewMapClient returns a MapClient backed by the package-level Fixture map.
// SourceRef reports the chart tag from the vendored snapshot header.
func NewMapClient() *MapClient {
	return &MapClient{
		fixture: Fixture,
		source:  SourceRef{ChartTag: FixtureChartTag, SHA: FixtureSHA},
	}
}

func (c *MapClient) ListWorkflows(_ context.Context) ([]WorkflowSummary, SourceRef, error) {
	out := make([]WorkflowSummary, 0, len(c.fixture))
	for _, g := range c.fixture {
		out = append(out, g.WorkflowSummary)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, c.source, nil
}

func (c *MapClient) GetWorkflow(_ context.Context, name string) (WorkflowGraph, SourceRef, error) {
	g, ok := c.fixture[name]
	if !ok {
		return WorkflowGraph{}, c.source, fmt.Errorf("%w: %s", ErrWorkflowNotFound, name)
	}
	return g, c.source, nil
}
